import { yamlList, yamlScalar } from './yaml.mjs'
import { isGenerationModel } from './model-metadata.mjs'

export function buildCpaConfig(config, channels, routes, runtimePaths) {
  const gateway = config.gateway
  const cpaPort = Number(runtimePaths.cpaPort)
  if (!Number.isInteger(cpaPort) || cpaPort <= 0 || cpaPort > 65535) throw new Error(`Invalid internal CPA port: ${cpaPort}`)
  const lines = [
    '# Generated by cpa-channel-gateway. Do not edit by hand.',
    `host: ${yamlScalar(gateway.internal.host)}`,
    `port: ${cpaPort}`,
    'tls:',
    '  enable: false',
    `auth-dir: ${yamlScalar(runtimePaths.authDir)}`,
    'api-keys:',
    `  - ${yamlScalar(config.gatewayKey)}`,
    'debug: false',
    'remote-management:',
    `  allow-remote: false`,
    `  disable-control-panel: ${yamlScalar(!config.managementKey)}`,
    ...(config.managementKey ? [`  secret-key: ${yamlScalar(config.managementKey)}`] : ['  secret-key: ""']),
    'pprof:',
    '  enable: false',
    'plugins:',
    '  enabled: false',
    'usage-statistics-enabled: false',
    'logging-to-file: false',
    `logs-max-total-size-mb: ${gateway.cpa.logsMaxTotalSizeMb}`,
    `request-retry: ${gateway.cpa.requestRetry}`,
    `max-retry-credentials: ${gateway.cpa.maxRetryCredentials}`,
    `max-retry-interval: ${gateway.cpa.maxRetryIntervalSeconds}`,
    'disable-cooling: false',
    'save-cooldown-status: true',
    'disable-claude-cloak-mode: true',
    'claude-code:',
    '  disable-cloaking-model-list: true',
    'codex:',
    '  identity-confuse: false',
    `  disable-codex-cloaking: ${yamlScalar(gateway.cpa.disableCodexCloaking ?? true)}`,
    '  optimize-multi-agent-v2: false',
    'routing:',
    '  strategy: fill-first',
    '  session-affinity: true',
    '  session-affinity-ttl: "1h"'
  ]

  const enabled = channels.filter(item => item.runtimeEnabled ?? item.enabled)
  const compatible = protocolViews(enabled, 'openai-compatible')
  const responses = protocolViews(enabled, 'responses')
  const claude = protocolViews(enabled, 'claude')
  if (compatible.length) {
    lines.push('openai-compatibility:')
    for (const channel of compatible) renderOpenAiCompatible(lines, config, channel, routes)
  }
  if (responses.length) {
    lines.push('codex-api-key:')
    for (const channel of responses) renderNativeKey(lines, config, channel, routes, { codex: true })
  }
  if (claude.length) {
    lines.push('claude-api-key:')
    for (const channel of claude) renderNativeKey(lines, config, channel, routes, { codex: false })
  }
  return lines.join('\n') + '\n'
}

function protocolViews(channels, protocol) {
  return channels
    .map(channel => ({ ...channel, models: channel.models.filter(model => model.protocol === protocol && model.status !== 'disabled' && isGenerationModel(model)) }))
    .filter(channel => channel.models.length > 0)
}

function renderOpenAiCompatible(lines, config, channel, routes) {
  lines.push(
    `  - name: ${yamlScalar(`channel-${channel.id}`)}`,
    '    disabled: false',
    `    base-url: ${yamlScalar(buildLocalBaseUrl(config.gateway, channel, 'openai-compatible'))}`,
    '    disable-cooling: false',
    '    request-retry: 0',
    '    api-key-entries:',
    `      - api-key: ${yamlScalar(channel.apiKey)}`,
    '        weight: 1',
    '    models:'
  )
  renderChannelModels(lines, channel, routes)
}

function renderNativeKey(lines, config, channel, routes, { codex }) {
  const protocol = codex ? 'responses' : 'claude'
  lines.push(
    `  - api-key: ${yamlScalar(channel.apiKey)}`,
    '    weight: 1',
    '    disable-cooling: false',
    '    request-retry: 0',
    `    base-url: ${yamlScalar(buildLocalBaseUrl(config.gateway, channel, protocol))}`
  )
  if (codex) lines.push('    websockets: false', '    alpha-search: false')
  else lines.push('    rebuild-mid-system-message: false', '    cloak:', '      mode: "never"')
  lines.push('    models:')
  renderChannelModels(lines, channel, routes)
}

function renderChannelModels(lines, channel, routes) {
  const modelEntries = []
  for (const model of channel.models.filter(item => item.status !== 'disabled' && isGenerationModel(item))) {
    for (const alias of model.aliases) modelEntries.push(renderModel(model, alias))
  }
  for (const route of routes.stableAliases.filter(item => item.channel === channel.id)) {
    const model = channel.models.find(item => item.upstream === route.model)
    if (model && model.status !== 'disabled' && isGenerationModel(model)) modelEntries.push(renderModel(model, route.alias))
  }
  for (const route of routes.pinnedAliases.filter(item => item.channel === channel.id)) {
    const model = channel.models.find(item => item.upstream === route.model)
    if (model && model.status !== 'disabled' && isGenerationModel(model)) modelEntries.push(renderModel(model, route.alias))
  }
  for (const entry of modelEntries) lines.push(...entry)
}

export function buildLocalBaseUrl(gateway, channel, protocol) {
  let upstreamPath = channel.upstream.pathname === '/'
    ? ''
    : channel.upstream.pathname.replace(/\/+$/, '')

  // CPA's Claude executor appends /v1/messages while its OpenAI executors append
  // /responses or /chat/completions. Keep the upstream base path in CPA instead
  // of asking HAProxy to prepend it blindly, and remove one terminal /v1 only
  // for Claude so /v1/v1/messages can never be produced.
  if (protocol === 'claude' && upstreamPath.endsWith('/v1')) {
    upstreamPath = upstreamPath.slice(0, -3)
  }
  return `http://${gateway.internal.host}:${channel.listener}${upstreamPath}`
}

function renderModel(model, alias) {
  if (!model) throw new Error(`Route references model that is not declared: ${alias}`)
  const lines = [
    `      - name: ${yamlScalar(model.upstream)}`,
    `        alias: ${yamlScalar(alias)}`,
    `        input-modalities: ${yamlList(model.inputModalities)}`,
    `        output-modalities: ${yamlList(model.outputModalities)}`
  ]
  if (model.displayName) lines.push(`        display-name: ${yamlScalar(model.displayName)}`)
  if (model.maxContextLength) lines.push(`        max-context-length: ${model.maxContextLength}`)
  if (model.thinkingLevels?.length) lines.push(`        thinking:\n          levels: ${yamlList(model.thinkingLevels)}`)
  return lines
}
