export function buildHaproxyConfig(config, channels) {
  const lines = [
    '# Generated by cpa-channel-gateway. Do not edit by hand.',
    'global',
    '  log stdout format raw local0',
    '  maxconn 128',
    '',
    'defaults',
    '  log global',
    '  mode http',
    '  option httplog',
    '  option http-keep-alive',
    '  retries 0',
    `  timeout connect ${config.timeouts.connectSeconds}s`,
    `  timeout client ${config.timeouts.clientSeconds}s`,
    `  timeout server ${config.timeouts.serverSeconds}s`,
    `  timeout queue ${config.queue.timeoutSeconds}s`,
    ''
  ]
  for (const channel of channels.filter(item => item.runtimeEnabled ?? item.enabled)) {
    const listener = channel.listener
    const backend = `channel_${channel.id.replaceAll('-', '_')}`
    const upstream = channel.upstream
    const upstreamHost = upstream.hostname.includes(':') ? `[${upstream.hostname}]` : upstream.hostname
    const address = `${upstreamHost}:${upstream.port || (upstream.protocol === 'https:' ? 443 : 80)}`
    lines.push(
      `frontend ${backend}_frontend`,
      `  bind ${config.internal.host}:${listener}`,
      '  mode http',
      `  default_backend ${backend}`,
      '',
      `backend ${backend}`,
      '  mode http',
      '  option http-keep-alive',
      '  option http-no-delay',
      '  http-reuse never',
      '  retries 0'
    )
    lines.push(`  http-request set-header Host ${escapeHaproxyValue(upstream.host)}`)
    lines.push('  http-request del-header Proxy-Connection')
    const tls = upstream.protocol === 'https:'
      ? ` ssl verify required ca-file /etc/ssl/certs/ca-certificates.crt sni str(${escapeHaproxyValue(upstream.hostname)}) check-sni ${escapeHaproxyValue(upstream.hostname)} alpn http/1.1`
      : ''
    lines.push(`  server upstream ${address}${tls} maxconn ${config.queue.maxConnectionsPerChannel} maxqueue ${config.queue.maxQueuedPerChannel} check`)
    lines.push('')
  }
  if (!channels.some(item => item.runtimeEnabled ?? item.enabled)) {
    lines.push('# No enabled channels. Enable at least one channel before starting CPA.')
  }
  return lines.join('\n') + '\n'
}

function escapeHaproxyValue(value) {
  if (!/^[A-Za-z0-9._:-]+$/.test(value)) throw new Error(`Unsupported upstream host: ${value}`)
  return value
}

export function assignListeners(channels, firstPort) {
  let port = firstPort
  return channels.map(channel => ({ ...channel, listener: port++ }))
}
